아이템 삭제 기능 수정 & 전체 체크박스 가능
JIandBabies/vin-co pull request #24
Opened 2022-12-16 06:35 UTC by dreamchach

2022-12-16 07:13 UTC, yujiseok requested changes
고생하셨어요 지영님 수정사항 보시고 수정해주시면 머지할게요~

2022-12-16 07:13 UTC, yujiseok commented on src/pages/cart/Cart.jsx
> +  const [checkItems, setCheckItems] = useState([]);
```suggestion
  const [items, setItems] = useState(list);
  const [checkItems, setCheckItems] = useState([]);
  
  const deleteHandler = (name) => {
    setItems(items.filter((item) => item.name !== name));
  };

  useEffect(() => {
    localStorage.setItem("item", JSON.stringify(items));
  }, [items]);

  const sumItems = items.reduce(
    (acc, item) => acc + item.price * item.number,
    0,
  );
```

state를 위로 올리면 좀 더 보기 쉬울 거 같아요!

2022-12-16 07:13 UTC, yujiseok commented on src/pages/cart/Cart.jsx
> +      setCheckItems(checkItems.filter((el) => el !== id));
```suggestion
      setCheckItems(checkItems.filter((checkItem) => checkItem !== id));
```

el 대신 checkItem 으로 파라미터를 바꾼다면 좀 더 가독성이 올라가지 않을까요?

2022-12-16 07:13 UTC, yujiseok commented on src/pages/cart/Cart.jsx
> +      items.forEach((el) => idArray.push(el.id));
여기도 마찬가지 입니다!

2022-12-16 07:13 UTC, yujiseok commented on src/pages/cart/Cart.jsx
> +          {" "}
지워주세요!

2022-12-16 12:22 UTC, dreamchach commented
곧 고쳐서 올릴게요

2022-12-17 12:23 UTC, merged

2022-12-17 12:23 UTC, yujiseok commented
고생하셨어요